workflow: hotfix
phase: archive
build_mode: direct
isolation: branch
verify_mode: light
base_ref: 89b5c9a052c7659e794a2ffaba47a5871913f76c
design_doc: null
plan: null
verify_result: pass
verification_report: null
branch_status: pending
created_at: 2026-06-02
verified_at: 2026-06-02
archived: true
